import type { NextPage } from "next";
import Head from "next/head";
import { MainContainer } from "../../src/components/container/mainContainer";
import { Footer } from "../../src/components/footer/Footer";
import HeroSection from "../../src/components/heroHeader/Hero";
import NavBar from "../../src/components/navbar/Navbar";
import Ads from "../home/Ads";
import Articles from "../home/Articles";
import { HeighLightNews } from "../home/HeighlightNews";
import MostView from "../home/MostView";

// here we test Ui responsive design 

const ReportAndStudies: NextPage = () => {
  return (
    <div dir="ltr">
      <Head>
        <title>Debugs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HeroSection
        heading="Central blog"
        content="there is a huge amount of rendering to applay here "
      />
      <MainContainer>
        <HeighLightNews />
        <Articles />
        <Ads />
        <MostView />
      </MainContainer>
      <Footer/>
    </div>
  );
};

export default ReportAndStudies;
